// Auto-generated. Do not edit!

// (in-package puzzlebot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class GoToPoseGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_pose2d = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_pose2d')) {
        this.goal_pose2d = initObj.goal_pose2d
      }
      else {
        this.goal_pose2d = new geometry_msgs.msg.Pose2D();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GoToPoseGoal
    // Serialize message field [goal_pose2d]
    bufferOffset = geometry_msgs.msg.Pose2D.serialize(obj.goal_pose2d, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GoToPoseGoal
    let len;
    let data = new GoToPoseGoal(null);
    // Deserialize message field [goal_pose2d]
    data.goal_pose2d = geometry_msgs.msg.Pose2D.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'puzzlebot_msgs/GoToPoseGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e2e5ecf04a128dd1a7f1078890fdf001';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal         
    geometry_msgs/Pose2D goal_pose2d
    
    ================================================================================
    MSG: geometry_msgs/Pose2D
    # Deprecated
    # Please use the full 3D pose.
    
    # In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.
    
    # If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.
    
    
    # This expresses a position and orientation on a 2D manifold.
    
    float64 x
    float64 y
    float64 theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GoToPoseGoal(null);
    if (msg.goal_pose2d !== undefined) {
      resolved.goal_pose2d = geometry_msgs.msg.Pose2D.Resolve(msg.goal_pose2d)
    }
    else {
      resolved.goal_pose2d = new geometry_msgs.msg.Pose2D()
    }

    return resolved;
    }
};

module.exports = GoToPoseGoal;
