; Auto-generated. Do not edit!


(cl:in-package puzzlebot_msgs-msg)


;//! \htmlinclude GoToPoseGoal.msg.html

(cl:defclass <GoToPoseGoal> (roslisp-msg-protocol:ros-message)
  ((goal_pose2d
    :reader goal_pose2d
    :initarg :goal_pose2d
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass GoToPoseGoal (<GoToPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name puzzlebot_msgs-msg:<GoToPoseGoal> is deprecated: use puzzlebot_msgs-msg:GoToPoseGoal instead.")))

(cl:ensure-generic-function 'goal_pose2d-val :lambda-list '(m))
(cl:defmethod goal_pose2d-val ((m <GoToPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader puzzlebot_msgs-msg:goal_pose2d-val is deprecated.  Use puzzlebot_msgs-msg:goal_pose2d instead.")
  (goal_pose2d m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToPoseGoal>) ostream)
  "Serializes a message object of type '<GoToPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_pose2d) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToPoseGoal>) istream)
  "Deserializes a message object of type '<GoToPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_pose2d) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToPoseGoal>)))
  "Returns string type for a message object of type '<GoToPoseGoal>"
  "puzzlebot_msgs/GoToPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToPoseGoal)))
  "Returns string type for a message object of type 'GoToPoseGoal"
  "puzzlebot_msgs/GoToPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToPoseGoal>)))
  "Returns md5sum for a message object of type '<GoToPoseGoal>"
  "e2e5ecf04a128dd1a7f1078890fdf001")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToPoseGoal)))
  "Returns md5sum for a message object of type 'GoToPoseGoal"
  "e2e5ecf04a128dd1a7f1078890fdf001")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToPoseGoal>)))
  "Returns full string definition for message of type '<GoToPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%geometry_msgs/Pose2D goal_pose2d~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToPoseGoal)))
  "Returns full string definition for message of type 'GoToPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%geometry_msgs/Pose2D goal_pose2d~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_pose2d))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToPoseGoal
    (cl:cons ':goal_pose2d (goal_pose2d msg))
))
