(cl:defpackage puzzlebot_msgs-msg
  (:use )
  (:export
   "<GOTOPOSEACTION>"
   "GOTOPOSEACTION"
   "<GOTOPOSEACTIONFEEDBACK>"
   "GOTOPOSEACTIONFEEDBACK"
   "<GOTOPOSEACTIONGOAL>"
   "GOTOPOSEACTIONGOAL"
   "<GOTOPOSEACTIONRESULT>"
   "GOTOPOSEACTIONRESULT"
   "<GOTOPOSEFEEDBACK>"
   "GOTOPOSEFEEDBACK"
   "<GOTOPOSEGOAL>"
   "GOTOPOSEGOAL"
   "<GOTOPOSERESULT>"
   "GOTOPOSERESULT"
  ))

