// Generated by gencpp from file puzzlebot_msgs/GoToPoseGoal.msg
// DO NOT EDIT!


#ifndef PUZZLEBOT_MSGS_MESSAGE_GOTOPOSEGOAL_H
#define PUZZLEBOT_MSGS_MESSAGE_GOTOPOSEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace puzzlebot_msgs
{
template <class ContainerAllocator>
struct GoToPoseGoal_
{
  typedef GoToPoseGoal_<ContainerAllocator> Type;

  GoToPoseGoal_()
    : goal_pose2d()  {
    }
  GoToPoseGoal_(const ContainerAllocator& _alloc)
    : goal_pose2d(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _goal_pose2d_type;
  _goal_pose2d_type goal_pose2d;





  typedef boost::shared_ptr< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPoseGoal_

typedef ::puzzlebot_msgs::GoToPoseGoal_<std::allocator<void> > GoToPoseGoal;

typedef boost::shared_ptr< ::puzzlebot_msgs::GoToPoseGoal > GoToPoseGoalPtr;
typedef boost::shared_ptr< ::puzzlebot_msgs::GoToPoseGoal const> GoToPoseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator1> & lhs, const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal_pose2d == rhs.goal_pose2d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator1> & lhs, const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace puzzlebot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2e5ecf04a128dd1a7f1078890fdf001";
  }

  static const char* value(const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2e5ecf04a128dd1ULL;
  static const uint64_t static_value2 = 0xa7f1078890fdf001ULL;
};

template<class ContainerAllocator>
struct DataType< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puzzlebot_msgs/GoToPoseGoal";
  }

  static const char* value(const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal         \n"
"geometry_msgs/Pose2D goal_pose2d\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose2d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPoseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puzzlebot_msgs::GoToPoseGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_pose2d: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose2d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUZZLEBOT_MSGS_MESSAGE_GOTOPOSEGOAL_H
